theme: jekyll-theme-minimal
title: Home of jonnybergdahl on GitHub
description: This site contains documentation for the projects I work on.
include:
  - growcube-client/_images/*
  - growcube-client/_static/*
  - */_static/js/*
  - */_static/css/*
