var annotated_dup =
[
    [ "JBStringHelper", "class_j_b_string_helper.html", null ],
    [ "JBTimeHelper", "class_j_b_time_helper.html", null ],
    [ "JBWoprBoardPins", "struct_j_b_wopr_board_pins.html", "struct_j_b_wopr_board_pins" ],
    [ "JBWoprConfiguration", "struct_j_b_wopr_configuration.html", "struct_j_b_wopr_configuration" ],
    [ "JBWoprDateDisplayEffect", "class_j_b_wopr_date_display_effect.html", "class_j_b_wopr_date_display_effect" ],
    [ "JBWoprDateDisplayRainbowEffect", "class_j_b_wopr_date_display_rainbow_effect.html", "class_j_b_wopr_date_display_rainbow_effect" ],
    [ "JBWoprDateTimeDisplayEffect", "class_j_b_wopr_date_time_display_effect.html", "class_j_b_wopr_date_time_display_effect" ],
    [ "JBWoprDateTimeDisplayRainbowEffect", "class_j_b_wopr_date_time_display_rainbow_effect.html", "class_j_b_wopr_date_time_display_rainbow_effect" ],
    [ "JBWoprDefconRainbowEffect", "class_j_b_wopr_defcon_rainbow_effect.html", "class_j_b_wopr_defcon_rainbow_effect" ],
    [ "JBWoprDevice", "class_j_b_wopr_device.html", "class_j_b_wopr_device" ],
    [ "JBWoprEffectBase", "class_j_b_wopr_effect_base.html", "class_j_b_wopr_effect_base" ],
    [ "JBWoprHAConfig", "struct_j_b_wopr_h_a_config.html", null ],
    [ "JBWoprHADevice", "class_j_b_wopr_h_a_device.html", "class_j_b_wopr_h_a_device" ],
    [ "JBWoprMissileCodeSolveEffect", "class_j_b_wopr_missile_code_solve_effect.html", "class_j_b_wopr_missile_code_solve_effect" ],
    [ "JBWoprMqttConfig", "struct_j_b_wopr_mqtt_config.html", "struct_j_b_wopr_mqtt_config" ],
    [ "JBWoprMqttDevice", "class_j_b_wopr_mqtt_device.html", "class_j_b_wopr_mqtt_device" ],
    [ "JBWoprNokiaTuneEffect", "class_j_b_wopr_nokia_tune_effect.html", "class_j_b_wopr_nokia_tune_effect" ],
    [ "JBWoprScrollTextDisplayEffect", "class_j_b_wopr_scroll_text_display_effect.html", "class_j_b_wopr_scroll_text_display_effect" ],
    [ "JBWoprSongEffect", "class_j_b_wopr_song_effect.html", "class_j_b_wopr_song_effect" ],
    [ "JBWoprTextDisplayEffect", "class_j_b_wopr_text_display_effect.html", "class_j_b_wopr_text_display_effect" ],
    [ "JBWoprTheRickEffect", "class_j_b_wopr_the_rick_effect.html", "class_j_b_wopr_the_rick_effect" ],
    [ "JBWoprTimeDisplayEffect", "class_j_b_wopr_time_display_effect.html", "class_j_b_wopr_time_display_effect" ],
    [ "JBWoprTimeDisplayRainbowEffect", "class_j_b_wopr_time_display_rainbow_effect.html", "class_j_b_wopr_time_display_rainbow_effect" ],
    [ "JBWoprWiFiConfiguration", "struct_j_b_wopr_wi_fi_configuration.html", "struct_j_b_wopr_wi_fi_configuration" ],
    [ "JBWoprWiFiDevice", "class_j_b_wopr_wi_fi_device.html", "class_j_b_wopr_wi_fi_device" ],
    [ "JBWoprXmasSecondsDisplayEffect", "class_j_b_wopr_xmas_seconds_display_effect.html", "class_j_b_wopr_xmas_seconds_display_effect" ]
];